import { MeiliSearch, type HybridSearch } from 'meilisearch'
import { logger } from '../logger.js'

const log = logger.child('search')

const MEILI_URL = process.env.MEILI_URL || 'http://localhost:7700'
const MEILI_MASTER_KEY = process.env.MEILI_MASTER_KEY || undefined

let client: MeiliSearch | null = null

export function getSearchClient(): MeiliSearch {
  if (!client) {
    client = new MeiliSearch({ host: MEILI_URL, apiKey: MEILI_MASTER_KEY })
  }
  return client
}

export const ARTICLES_INDEX = 'articles'
export const ARTICLES_STAGING_INDEX = 'articles_staging'

export interface MeiliArticleDoc {
  id: number
  feed_id: number
  category_id: number | null
  title: string
  /** Used by the embedder template (title + summary) — keeping keyword attributes unchanged */
  summary: string | null
  feed_type?: 'rss' | 'clip'
  full_text: string
  full_text_translated: string
  lang: string | null
  published_at: number // Unix timestamp (seconds) for numeric filtering
  score: number
  is_unread: boolean
  is_liked: boolean
  is_bookmarked: boolean
  /** Optional Meilisearch-managed embedding control (set to null to skip a document) */
  _vectors?: Record<string, null>
}

/**
 * Build a Meilisearch filter string from optional filter params.
 */
export function buildMeiliFilter(opts: {
  feed_id?: number
  category_id?: number
  since?: string
  until?: string
  unread?: boolean
  liked?: boolean
  bookmarked?: boolean
}): string | undefined {
  const parts: string[] = []
  if (opts.feed_id) parts.push(`feed_id = ${opts.feed_id}`)
  if (opts.category_id) parts.push(`category_id = ${opts.category_id}`)
  if (opts.since) parts.push(`published_at >= ${Math.floor(new Date(opts.since).getTime() / 1000)}`)
  if (opts.until) parts.push(`published_at <= ${Math.floor(new Date(opts.until).getTime() / 1000)}`)
  if (opts.unread !== undefined) parts.push(`is_unread = ${opts.unread}`)
  if (opts.liked) parts.push('is_liked = true')
  if (opts.bookmarked) parts.push('is_bookmarked = true')
  return parts.length > 0 ? parts.join(' AND ') : undefined
}

export interface MeiliSearchOptions {
  limit?: number
  offset?: number
  filter?: string
  sort?: string[]
}

export interface MeiliSearchResult {
  hits: { id: number }[]
  estimatedTotalHits: number
}

/**
 * Simple Meilisearch search — returns hit IDs in ranked order.
 */
export async function meiliSearch(
  query: string,
  opts?: MeiliSearchOptions,
): Promise<MeiliSearchResult> {
  const index = getSearchClient().index(ARTICLES_INDEX)
  return runMeiliSearch(index, query, opts, undefined)
}

export type SearchMode = 'keyword' | 'hybrid' | 'keyword-fallback'

export interface HybridSearchResult extends MeiliSearchResult {
  searchMode: SearchMode
}

async function runMeiliSearch(
  index: ReturnType<MeiliSearch['index']>,
  query: string,
  opts?: MeiliSearchOptions,
  hybrid?: HybridSearch,
): Promise<MeiliSearchResult> {
  const result = await index.search(query, {
    limit: opts?.limit ?? 20,
    offset: opts?.offset ?? 0,
    filter: opts?.filter,
    sort: opts?.sort,
    attributesToRetrieve: ['id'],
    ...(hybrid ? { hybrid } : {}),
  })
  return {
    hits: result.hits as { id: number }[],
    estimatedTotalHits: result.estimatedTotalHits ?? 0,
  }
}

/**
 * Hybrid semantic + keyword search with a keyword-only fallback.
 *
 * When `hybrid` is provided the query embedding is generated by
 * Meilisearch at query time. If that fails (embedding provider down,
 * misconfigured key, invalid query embedding), we retry the same query
 * once without the hybrid parameter so keyword results still come back.
 * A fallback is reported via `searchMode`, never by an empty response
 * caused only by an embedding failure.
 */
export async function searchArticlesWithHybrid(
  query: string,
  opts?: MeiliSearchOptions & { hybrid?: HybridSearch },
): Promise<HybridSearchResult> {
  const index = getSearchClient().index(ARTICLES_INDEX)
  if (!opts?.hybrid) {
    return { ...(await runMeiliSearch(index, query, opts, undefined)), searchMode: 'keyword' }
  }
  try {
    return { ...(await runMeiliSearch(index, query, opts, opts.hybrid)), searchMode: 'hybrid' }
  } catch (err) {
    log.warn('Hybrid search failed; falling back to keyword search:', err)
    return { ...(await runMeiliSearch(index, query, opts, undefined)), searchMode: 'keyword-fallback' }
  }
}
